### ISSUE TITLE
BACKEND: AUTHORIZATON: Admin Hash Table 

### ISSUE THREAD

**Issue by htharker42** [codeforpdx/dwellingly-app#103]
create a hash table model for the admin permission to verify if a user is an admin. 
should check the user id against the model and verify that they are indeed an admin

**Comment by mswanson-me** [comment]
Reference material: https://pythonprogramming.net/password-hashing-flask-tutorial/

**Comment by NickSchimek** [comment]
@htharker42 I'm not quire sure I understand the reasoning for creating a hash table to authorize a user. @mswanson-me referenced a link to password hashing which would be relevant for authentication, but not authorization. It seems we already have the functionality to check if a user is an admin. Can I get some clarification on what this issue is asking to do?

**Comment by htharker42** [comment]
issue no longer relevant - closing
