### ISSUE TITLE
BACKEND: Improve upon Logout functionality

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#141]
* Add a new /logout endpoint to the backend
* Create a new database table to keep track of the blacklisted access tokens with two columns
** access_token
** date
* If there's time, look into a CRON job to clear out the rows that are past "Now minus access_token lifespan" every day

**Comment by aedwardg** [comment]
Hey @asaltveit,

Are you still working on this?  I noticed it's been assigned to you since July and I just wanted to double check that you're making progress on it.  

If you need any help, feel free to reach out to other team members on GitHub or Slack with any questions you might have.

If you're not currently working on it and/or you don't think you'll be able to during the next week, please remove yourself from the `Assignees` section so that other team members can pick up this ticket.

Thanks!

**Comment by yunnie** [comment]
Do we only want to store tokens that are revoked? Basically, if the token is in the database it's revoked? Or do we want to store all tokens and an indicator to show if the token is revoked. In this case, if the token is not in the database then it's not valid. Is there a preference in design?

**Comment by yunnie** [comment]
@NickSchimek, @aedwardg, @Chris-Boe I think this is already done. A RevokedTokensModel already exists in 'models/revoked_tokens.py' and a function 'check_if_token_is_blacklist' is already defined in 'app.py'
