### ISSUE TITLE
BACKEND: Send updated JWT for PATCH requests to /api/user/:uid

### ISSUE THREAD

**Issue by yhafez** [codeforpdx/dwellingly-app#288]
**Purpose**
The json web token stored in local storage on the front-end should be a reflection of the most up-to-date information in the database, so when user information is updated through a PATCH request, an updated JWT should be sent to the front-end to update local storage with the newly updated information. 

**Proposed Solution**
Sign a new JWT with the newly updated user db information in the /api/user/:uid PATCH route and store it in a variable. Add the variable to the data being sent in response to successful requests.    

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Current response data, which includes user information, is still sent in response to successful PATCH requests
- [ ] A separate key, storing an updated JSON web token should also be included in the response object sent with successful PATCH requests 

**Mockup Screenshot or Page Number**
N/a

**Additional context**
When phone number and/or email are updated in settings, the database is successfully updated with the new information, however the JWT stored in local storage (which should reflect the database), becomes out of date. Currently, no new and updated JWT is sent over in response to a successful PATCH request which can be used to update local storage.

The data for the JWT in local storage should ideally be sources directly from the database, rather than updated on the front-end when a change is made in case of failure or bugs, and doing so would also require access to the JWT private key on the front-end to decode and then re-encode an updated JWT on the front-end, which adds overhead in the form of a few npm packages (jsonwebtoken, dotenv or similar, a new .env file), as well as security concerns involved with storing the JWT private key on the front-end.

**Comment by Chris-Boe** [comment]
Talked about this with the group and we'll need to make a couple more changes to support this. That PATCH route is used by admins to edit other users as well as users editing their own info. Here's what we'll need to change:
- [ ] Downgrade that API's permission check to `@jwt_required`
- [ ] Only allow the user to edit a _different_ user if they are an admin, otherwise reject with 403. If they are editing their own info, allow
- [ ] Only return the new tokens if they are editing their own account, otherwise just return the json with 201

**Comment by yhafez** [comment]
> Talked about this with the group and we'll need to make a couple more changes to support this. That PATCH route is used by admins to edit other users as well as users editing their own info. Here's what we'll need to change:
> 
> * [ ]  Downgrade that API's permission check to `@jwt_required`
> * [ ]  Only allow the user to edit a _different_ user if they are an admin, otherwise reject with 403. If they are editing their own info, allow
> * [ ]  Only return the new tokens if they are editing their own account, otherwise just return the json with 201

@Chris-Boe, super on-point as always 🙌

**Comment by jls-github** [comment]
Fixed those issues, @Chris-Boe - it should be working as intended now. 

https://github.com/codeforpdx/dwellinglybackend/pull/97

**Comment by jls-github** [comment]
It looks like the tests are failing for the build. I'm unfamiliar with testing in this setting, so I'm unsure of how to proceed. It is working functionally through my own testing, but I know that's not a good thing to rely on.

EDIT: fixed - There was an error in the user validation. I was validating that the user being edited was an admin, not the user making the edit. I also made it so that only admins may edit roles.
