### ISSUE TITLE
Add python style check for backend development

### ISSUE THREAD

**Issue by sokampdx** [codeforpdx/dwellingly-app#348]
**Purpose**
What will this feature provide?
Add style check to enforce consistent style for backend code. This will help code readability. This should not affect actual functionality or testing in backend.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
Hugh mentioned he tried flake8, and a few other style check that didn't play nice with flask. We should document the list to find the right solution.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] enforce style when running test. Fail the test for code not within the style guideline.

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
N/A

**Additional context**

**Comment by sokampdx** [comment]
@htharker42 Could you list the one you mentioned that you tried already? I only remember flake8.

**Comment by NickSchimek** [comment]
- On one end of the spectrum there is https://pep8speaks.com/ but that can generate a lot of noise in the PR regarding style fixes
- The other end of the spectrum there is a new and very opinionated styler https://github.com/psf/black which automatically converts code the way they see fit. And if we wanted to we could add a precommit git hook so that all code is formatted automatically - Although I would not recommend this for black as it is still in beta.

It's been my experience that devs have issues with either end of the spectrum. There could be a happy middle ground. I would prefer to stay away from style commits in the PR. There is also https://github.com/PyCQA/pycodestyle (formerly pep8). black looks the most promising, and is by far the most popular on github.

**Comment by NickSchimek** [comment]
Looks like the record sponge project uses black with a pre commit hook
https://github.com/codeforpdx/recordexpungPDX/blob/master/.pre-commit-config.yaml

**Comment by NickSchimek** [comment]
OK last comment. It seems flask uses black as a style checker too. It is probably the way to go.
https://github.com/pallets/flask/blob/master/CONTRIBUTING.rst#submitting-patches

**Comment by NickSchimek** [comment]
@sokampdx It looks like we already have a style linter installed in the Pipfile. It is the Flake8 dependency. I just ran it on our codebase and there are many infractions. It did not auto correct anything, and I don't see an option for that. I would lean towards removing this dep and install black as it is more widely used.

**Comment by aedwardg** [comment]
I was wondering about this as I went through the backend code.  I saw Flake8 was installed in the Pipfile so that's what I used for the linter for my last contribution (totally missed this issue).

The thing about Flake8 is that it checks for compliance with PEP 8 standards, and will give warnings when your code doesn't meet those standards, but it will stop there.  Without a code formatter, Flake8 (assuming each contributor has enabled it as their Python linter) will leave it up to the individual to alter their own code upon seeing the warnings.

In past projects I've used Flake8 as the linter with either [autopep8](https://pypi.org/project/autopep8/) or [Black](https://pypi.org/project/black/) as the formatter.  Either option is fine with me -- Black is a little more opinionated (converts all single quotes to double quotes by default 😂) but the resulting code looks nice and a lot of orgs have adopted it.  The main thing is that contributors can set up format-on-save with either one, and you can use a pre-commit hook to ensure it across the board.

The one thing to note is that Flake8 catches a lot of non-style-related things like syntax errors, unused imports, etc. that Black doesn't look for.  So, while Black can be used without Flake8, it might be better to first format with Black and then check with Flake8 afterward.  If we decide to go this route, we'll want to configure Flake8 to not throw warnings for a couple of Black's defaults ([example from Black docs](https://black.readthedocs.io/en/stable/compatible_configs.html#flake8)).

**Comment by NickSchimek** [comment]
That is very good information. Thank You! It sounds like a combination of Flake8 and Black would be useful. I've been purposely holding off on implementing this, however it is probably time to get something implemented. Let's talk more about this.

**Comment by NickSchimek** [comment]
@aedwardg Do you want to implement this for us?

**Comment by aedwardg** [comment]
Sure, I'll work on getting that set up. 💻
