### ISSUE TITLE
Create Unit tests for notes model

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#412]
**Purpose**
public methods should have tests

**Acceptance Criteria**
- [ ] Add the BaseInterfaceTest to `tests/unit/test_note.py` and create unit tests for all public methods. see [this commit](https://github.com/codeforpdx/dwellinglybackend/blob/31610de13449c002d2394bfa7b2e48a8c12e5b1e/tests/unit/test_lease.py) for an example.

**Comment by yunnie** [comment]
The notes model depends on the user and ticket models. The create_join_staff() fixture is available, but the ticket figure is still an open ticket.

We also need the schema for the Notes Model. Right now, it will throw an error because the schema is missing.

I did write a figure for the notes, but it's waiting for the ticket fixture. I assume that the ticket tests will need to tie the note and the ticket together, so it probably is a bad idea to just throw in a hard coded ticket id in the notes model.

**Comment by NickSchimek** [comment]
OK. sorry about that. I will add a blocker label to this issue. We should get the schemas created before doing this.

**Comment by NickSchimek** [comment]
Created issue #457 to get a schema created.
