### ISSUE TITLE
Remove the url_for helper methods in the emails with the FE specific route

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/dwellingly-app#461]
**Purpose**
url_for generates the link to the BE, but we need to direct the user to the FE page. There should be a config var that can be used to grab the base url that will be used in production.

**Comment by keppel2** [comment]
Shouldn't BE and FE base url be the same (production or otherwise)?

**Comment by aedwardg** [comment]
@keppel2, 

The problem is that the Flask `url_for()` function is returning the URL for the API endpoint rather than the frontend page.
What we want to do is include a constant in `config.py` for the frontend base url so that we can properly direct the user to the page.

For example, right now in the reset password email template we have code that looks something like this:
```html
<a href="{{ url_for('resetpassword', token=token, _method='GET', _external=True) }}">Reset Password Link</a>
```
This would actually send the user to the api endpoint (`/api/reset-password/token`), so they'd probably see a JSON rather than the reset password page.

Instead, we probably want to do something like this:
```html
<a href="{{ FRONTEND_BASE_URL }}/changePassword">Reset Password Link</a>
```

(or whatever the route will be to reset passwords on the frontend &mdash; I don't think they have a proper password reset page yet)

Currently, the frontend is running on localhost:3000 and accesses the API on localhost:5000 using `http-proxy-middleware`.

For the development environment, you could probably set `FRONTEND_BASE_URL` to `http://localhost:3000/`, but I'm not sure whether this will be the same in production.

**Comment by NickSchimek** [comment]
@keppel2 I believe your correct. The base_url should be the same in production, however they differ in development environments as @aedwardg mentioned. And all frontend endpoints will be relative to the base where as all backend endpoints are relative to the base + `/api`.  So again there is that little nuance that @aedwardg mentioned.
