### ISSUE TITLE
New endpoint to return Lease + Tenants on Lease

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#505]
**Purpose**
What will this feature provide?
We want an endpoint that will give us all the necessary info for the list of tenants on pages 49/50 of the Dwellingly mockups https://drive.google.com/file/d/1YqboQogczYm1HkyRqEtVSzeQ61T9hWU2/view

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
* New method in the LeaseModel to query by property and get all tenant information on the lease
* New class/endpoint in Property resource to get all leases + tenant information associated with the property

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ]

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.
![image](https://user-images.githubusercontent.com/8600792/103849495-a7a74200-5059-11eb-8e6e-68ddb7f0358f.png)

**Additional context**

**Comment by NickSchimek** [comment]
The relationships are all in place to provide this information. I don't think a query in the lease model is necessary.

The information can be reached by getting all leases for the given `property.leases`
and then for each lease get the tenant info
`lease.tenant`

I would say this is more of a serialization issue rather than a new endpoint issue. Could utilize marshmallow to handle all of this, but a quick solution would be to update the existing `json` method on the `property model` to return `tenants` or attach the results of `lease.tenant` into the existing `property.json` method. Many different ways to do the serializing part.

I would propose using the existing get endpoint that retrieves a property.
Specifically the `get` endpoint on the `property` class https://github.com/codeforpdx/dwellinglybackend/blob/development/resources/property.py#L76

And then you can get all the tenants for that property by doing something like:
```
tenants = []
for lease in property.leases:
    tenants.append(lease.tenant)
```

If using marshmallow than the above code would not be necessary, but we're not really using it for serializing so... The above code would get you all the tenants for the property. Merge the results of that into the existing json response and send to the FE.

Let me know what you think.
