### ISSUE TITLE
React Bootstrap tables are unusable on mobile

### ISSUE THREAD

**Issue by beekman** [codeforpdx/dwellingly-app#548]
**Describe the bug**
React Bootstrap tables used on the Properties, Property Managers, Tickets, and JOIN Staff pages are unusable on mobile.

**To Reproduce**
1. Use responsive mode or a mobile device to view the Properties, Property Managers, Tickets, and JOIN Staff pages.
2. See that many of the table rows are offscreen and unscrollable

**Expected behavior**
Because it's so important that the information in each row appear below its table header, probably the easiest fix is to make the tables scrollable horizontally so that all rows can be viewed.

**Screenshots**
<img width="948" alt="Screen Shot 2021-03-04 at 9 13 04 AM" src="https://user-images.githubusercontent.com/563233/110002058-dc3a2180-7cc9-11eb-8542-10f9109e448c.png">

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Smartphone (please complete the following information):**
 - Device: iPhone tested; the problem is on all mobile devices though.
 - OS: All
 - Browser: All
 - Version: All

**Additional context**
The styles causing problems seem to stem from .react-bootstrap-table and its children, which were not designed to work with mobile.

**Comment by Chris-Boe** [comment]
A common solution (that would take longer) would be to have only a couple of the most important cells of each row shown in the table, and when they click somewhere in the row, it would expand a card-like area displaying the rest of the information vertically (the "Transformed" solution here: https://medium.com/appnroll-publication/5-practical-solutions-to-make-responsive-data-tables-ff031c48b122).

Another option since we have the main view page for our tabled objects (Properties, Tenants, etc), is to only show them the main columns that would fit on a mobile screen, and make sure it's obvious they can click into the object to view the rest of the details.

**Comment by beekman** [comment]
@Chris-BoeI really like those ideas, but they would require more customization for each instance of the tabled objects, and I'd want to clarify those customizations. Perhaps we could discuss these options further tonight?

**Comment by Chris-Boe** [comment]
Found some good docs for the current table library we're using for implementing the expandable row functionality!

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-row-expand.html

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Basic%20Row%20Expand&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
