### ISSUE TITLE
define testing strategy for frontend (javascript/react)

### ISSUE THREAD

**Issue by deric4** [codeforpdx/dwellingly-app#55]
While the decision to use pytest for python was essentially unanimous, there wasn't a strong opinion on which testing framework to use for javascript/react code. Please add anything you feel might be left out or provide feedback! 

Options that were mentioned:

**Frameworks**
1. [jest](https://jestjs.io)

**React Component Testing**
1. [enzyme](https://airbnb.io/enzyme/)
    _thoughtworks tech radar prefers react-testing-library https://www.thoughtworks.com/radar/languages-and-frameworks_

1. [react-testing-library](https://testing-library.com/docs/intro)
     *not a testing framework but seems popular*

**Integration / End to End**
1. [cypress](https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell)

**Reference**
https://github.com/enaqx/awesome-react#react-testing

https://www.thoughtworks.com/radar/languages-and-frameworks

**Comment by sternmd** [comment]
@Deric4 thanks for the breakdown. I need practice on this too, so def willing to help you out 👍

Since we're already using create-react-app, I recommend testing the frontend with Jest and Enzyme. It's highly compatible/supported and `src/setupTests.js` is already built into our app for this exact purpose. 

I created a branch `fe-test-branch` where installed enzyme/jest, and set up a _very_ basic config for the Header component. Please note, this is the same exact header component that was originally in App.js, but moved into its own component. 

Simply run `npm test` in the terminal, once initialized type "w" for options, then "a" to run all tests.

**Comment by mhunterak** [comment]
We could also implement Selenium for UX testing when we get to that point

**Comment by sternmd** [comment]
Merged -> closing
