### ISSUE TITLE
Add a 'pending' user to the seed data

### ISSUE THREAD

**Issue by devon-wolf** [codeforpdx/dwellingly-app#577]
**Purpose**
What will this feature provide?

This is linked to frontend issue [#214](https://github.com/codeforpdx/dwellingly-app/issues/214) - we need a test user to reflect a new user who has not yet been assigned a role.

From the related issue:
>Currently, when a user first registers and logs in. They are brought to the standard dashboard. However, they lack the role required to make a couple of the api requests, so they are faced with errors and other things they shouldn't see until they are assigned a role.

**Proposed Solution**
In addition to the existing test users, save a test user to the database in seedData.py with the initial unassigned role (which I think defaults to 'None').

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] User exists in the seed data with no assigned role

**Additional Context**
I did notice there's a popup message after registering that indicates the user will be unable to login until their account has been approved, so it seems possible the intention is to not allow access until the user does, in fact, have a role assigned? If that's the case this issue and the one it's related to might be moot, but I'm opening this to complement the other issue assuming it is actually possible to land on a dashboard without a role.

**Comment by aedwardg** [comment]
@devon-wolf, thanks for bringing this up.

We actually have 4 "pending" users who are currently seeded into the database.  You can find their information here:
https://github.com/codeforpdx/dwellinglybackend/blob/a27d639f999d8471e75a214d68f67541b038d3a1/data/seedData.py#L71-L108

> I did notice there's a popup message after registering that indicates the user will be unable to login until their account has been approved, so it seems possible the intention is to not allow access until the user does, in fact, have a role assigned?

That's correct, when a new user registers with the app, they will not be able to access the app until an Admin or Staff member assigns them a role. If you sign in with one of the Admin test users, you can see there is a section at the bottom of the dashboard titled "Request for Access".  This section contains a list of the "pending" users who are awaiting approval and they can bee assigned a role by pressing the <kbd>Add</kbd> button:

![image](https://user-images.githubusercontent.com/44326005/113973703-95bc7300-97f1-11eb-9193-b8246153fd00.png)


We no longer have the exact problems described in #214, since now "pending" users are not authorized to access the dashboard at all.  
However, @htharker42 may want to still have some sort of page for those users to see when they try to sign in, instead of just showing them an error when they try to log in:

![image](https://user-images.githubusercontent.com/44326005/113973610-6efe3c80-97f1-11eb-8995-b0eec4e1ae2a.png)

If you're interested in working on that issue, the best thing to do would be to reach out to Hugh directly on Slack and see if he still wants that feature and what he had in mind for it.

**Comment by NickSchimek** [comment]
Closing this as there are pending users in the seed data. If we want to show a different error when a pending user tries to log in then let's open an appropriate issue labeled as such.

**Comment by devon-wolf** [comment]
Thanks! Just got a chance to look at this again - your explanation clears up a lot of confusion I had, which mostly comes down to that previous issue being out of date. I'll check in tomorrow about whether we want to add the dashboard for non-approved users as opposed to just denying login, thanks again for the thorough clarification!

**Comment by NickSchimek** [comment]
Cool. glad things are clearer now.

> I'll check in tomorrow about whether we want to add the dashboard for non-approved users as opposed to just denying login

This has been discussed in the past. We are not going to allow non-approved users any access to the system. I'd go as far to say that even allowing them to see a dashboard is a security risk. I do think it makes sense to say that "You are not approved" or something similar rather than "Failure signing in", because it is not a failure if the credentials are correct, It's just that they're not authorized. This might be a backend issue if the frontend is simply replaying the message that the backend sends.
