### ISSUE TITLE
Backend should pull user's ID from JWT when necessary

### ISSUE THREAD

**Issue by Chris-Boe** [codeforpdx/dwellingly-app#610]
**Purpose**
What will this feature provide?
Currently, the API's to change a user's settings or password, the user's ID is sent along from the frontend to the backend in the request, but the better way to do this is to have the backend just pull the ID from the JWT. This is more secure and removes an unnecessary request parameter.

**Proposed Solution**
If you have an idea on how to implement this feature, please share!
Change the backend API's for changing a user's password and email/phone settings to use the ID from the JWT in the request instead of from a parameter. We can also update the frontend to stop sending that parameter.

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Backend resources pull ID from JWT instead of request parameter

**Mockup Screenshot or Page Number**
Paste a screenshot of the feature from the FIGMA mockups or cite the page number.

**Additional context**

**Comment by aedwardg** [comment]
I agree that the front end probably shouldn't need to pull information from the JWT, but I don't think we should change the endpoint to use the JWT instead of the user id request parameter.  

If we do this, we limit users to only changing their own information.  So if an admin needs to change the settings of another user (such as when they grant access and assign roles to new users) they can no longer do so.

**Comment by NickSchimek** [comment]
> Currently, the API's to change a user's settings or password, the user's ID is sent along from the frontend to the backend in the request, but the better way to do this is to have the backend just pull the ID from the JWT. This is more secure and removes an unnecessary request parameter.

There is not a security risk from sending the id of the resource that needs to be updated. The backend authorizes the jwt sent along with request to ensure that the individual requesting the change/udpate is authorized to do so.

I think what your suggesting is that we remove the `:id` from the endpoint url, which is something that we do not want to do. When the endpoint includes a specific resource id than that identifies the resource we will be working on, and the action that will be invoked. The backend is not going to assume that a request sent without a resource id is going to operate on the resource identified in the jwt. It's best to be explicit in requests rather than to infer what a requester may have wanted to do.
