### ISSUE TITLE
Reverse order notes are returned from backend

### ISSUE THREAD

**Issue by Protopaco** [codeforpdx/dwellingly-app#612]
**Purpose**
When displaying the notes on the ticket modal, we want the the tickets to be displayed newest to oldest.  Rather than reversing the list in the frontend, we are hoping to pull the information from the database in the reverse order.

**Proposed Solution**
In the TicketModal we can reverse the array of notes assigned to each ticket.  Lines 33 & 34:

```python
for note in reversed(self.notes):
   message_notes.append(note.json())
```

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Notes array are returned newest to oldest

**Additional context**
If this is best done in the front it could be handled there instead.

**Comment by NickSchimek** [comment]
Thanks for bringing up this issue. I believe we do want the notes on the ticket to be displayed in the order you mentioned.

However, the backend currently doesn't do any ordering on the notes, or any resource for that matter. And simply reversing the order will not guarantee the notes are ordered from newest to oldest.

Whether this is done in the backend, or in the frontend, we'll want to be sure to order by the `created_at` field.

We currently serialize the `created_at` field when returning a `note` object

https://github.com/codeforpdx/dwellinglybackend/blob/f992e165ce7beb238be2f52d878b4e3e27e5a28c/models/notes.py#L22

Although the format we return it in is probably not the best for ordering. 

The reason why the backend doesn't do any ordering whatsoever is that it was decided, quite a long time ago, that the frontend would handle all ordering and sorting. Because of this I either want to be all in or not do it at all in the backend.

With that said, I kinda want to push this on to the frontend until the day we want to have some kind of ordering option available when backend requests are made.

So I think what should change is the format the created_at date is returned so that it is easier to order by that field in the frontend, since you'll want to be sure to order by the created_at date instead of simply reversing the order.

I'm hesitant to say that the frontend is the best place to do this, but that was the decision that had already been made quite some time ago.

**Comment by NickSchimek** [comment]
Issue #615 created to update the format for the created_at timestamp.

**Comment by Protopaco** [comment]
I wasn't aware that decision had been made.  Thank you for the update, I can 100% handle it in the frontend.  If the day comes when we want to change the system, we can address it then.
