### ISSUE TITLE
Attempting to grant a user access returns a 400

### ISSUE THREAD

**Issue by TNorbury** [codeforpdx/dwellingly-app#709]
**Describe the bug**
When granting access to a user via the Request Access page, a 400 error is returned when access is granted

**To Reproduce**
1. From the admin dashboard, click on a user under the "Request for Access section"
2. Choose a role and hit "Grant Access"
3. A message will pop up saying "Request failed with status code 400"

**Expected behavior**
I expect the user to be granted access (I assume, I'm actually ignorant of what the expected behavior is

**Screenshots**
![image](https://user-images.githubusercontent.com/16006381/136679523-be6ea058-1bc5-44bf-8a75-64d454bf377e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (WSL)
 - Browser Firefox
 - Version 92.0.1

**Comment by Chris-Boe** [comment]
Thanks @TNorbury ! I was just about to create a similar issue. I believe another symptom of the root issue is a 400 when attempting to change the phone number on the settings page. It seems the backend won't let us update any property on a user because it thinks the email must be different from what's already there on the user.

**Comment by Chris-Boe** [comment]
Another example of this is editing anything about a Property Manager without changing the email address
